version: '3'

services:
  kea:
    build: .
    container_name: kea-dhcp
    restart: unless-stopped
    volumes:
      - ./kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 67:67
    network_mode: host
