version: '3'

services:
  kea-dhcp-mgmt:
    # build: .
    image: widecamp1903/kea-dhcp
    container_name: kea-dhcp-mgmt
    restart: unless-stopped
    volumes:
      - ./4000_mgmt.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 67:67
    networks:
      vid4000:

  kea-dhcp-noc-private:
    # build: .
    image: widecamp1903/kea-dhcp
    container_name: kea-dhcp-noc-private
    restart: unless-stopped
    volumes:
      - ./4010_noc-private.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 67:67
    networks:
      vid4010:

  kea-dhcp-cmap-guest:
    # build: .
    image: widecamp1903/kea-dhcp
    container_name: kea-dhcp-camp-guest
    restart: unless-stopped
    volumes:
      - ./4030_camp-guest.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 67:67
    networks:
      vid4030:

  kea-dhcp-cmap-guest-nofw:
    # build: .
    image: widecamp1903/kea-dhcp
    container_name: kea-dhcp-camp-guest-nofw
    restart: unless-stopped
    volumes:
      - ./4031_camp-guest-nofw.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 67:67
    networks:
      vid4031:

  kea-dhcp-cmap-guest-isp:
    # build: .
    image: widecamp1903/kea-dhcp
    container_name: kea-dhcp-camp-guest-isp
    restart: unless-stopped
    volumes:
      - ./4032_camp-guest-isp.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 67:67
    networks:
      vid4032:

networks:
  mgmt:
    vid4000:
      mame: mgmt

    vid4010:
      mame: noc-private

    vid4030:
      mame: camp-guest

    vid4031:
      mame: camp-guest-nofw

    vid4032:
      mame: camp-guest-isp
